#!/bin/bash

SCREEN_TIMEOUT=60

# wlr-randr --output DPI-1 --mode 800x480 &

if (( SCREEN_TIMEOUT > 0 )); then
    swayidle -w \
        timeout "$SCREEN_TIMEOUT" 'wlopm --off "*"' \
        resume 'wlopm --on "*"' &
fi

swaybg -i /home/pi/raspap_web_display/labwc/background.png -m fill &

squeekboard &

chromium --app=http://localhost:8085 \
    --start-maximized \
    --disable-infobars \
    --ozone-platform=wayland